
name: Main Workflow
on: 
  push
jobs:
  steps:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: install NodeJs
        uses: actions/setup-node@v3
        with:
            node-version: 18.17.0
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
